CRAFT_ITEM_CREEPER_SOUND_PROBABILITY: 10
BLOCK_BREAK_CREEPER_PROBABILITY: 5
CREEPER_EXPLOSION_PRIMED_PROBABILITY: 3
BOAT_LIGHTNING_PROBABILITY: 20
NETHER_NOT_CREEPER_PROBABILITY: 5
END_GHAST_PROBABILITY: 5
SUPER_CREEPER_PROBABILITY: 10
POWERED_CREEPER_PROBABILITY: 3